#!/bin/bash

for i in "sol" "checker"
do
	if test -e $i
	then
		rm -rv $i
	fi
done

cd ../data/
for i in "bruteforce.out" "checker.out" "diff" "in.in" "out.out" "sol.out"
do
	if test -e $i
	then
		rm -rv $i
	fi
done
