#!/bin/bash

# Compile solution
if ! test -e exe/sol
then
	g++ src/sol.cpp -o exe/sol
	echo -e "src/sol.cpp compiled"
fi
if ! test -e exe/sol2
then
	g++ src/sol2.cpp -o exe/sol2
	echo -e "src/sol2.cpp compiled"
fi
if ! test -e exe/datagen
then
	g++ src/datagen.cpp -o exe/datagen
	echo -e "src/datagen.cpp compiled\n"
fi

# Generate input data

# Run the program
cd data
echo "Running..."
../exe/sol < data.in > out.out
../exe/sol2 < data.in > out2.out
cnt=1
while diff out.out out2.out
do
	../exe/datagen > in.in
	echo $cnt: inputdata generated
	time ../exe/sol < in.in > out.out
	time ../exe/sol2 < in.in > out2.out
	cnt=$[$cnt+1]
	# echo $cnt no problem
done

# time ./sol < ../data/in.in > ../data/out.out
echo -e "\nProgram finished\n"
