#include <cstdio>
#include <cstring>
#include <algorithm>
using namespace std;
const int maxn = 1000010;

char str[maxn];
int len, Next[maxn];
bool esc = false;

void Get_next(){
	int i = 0, j = -1;
	memset(Next, 0, sizeof(Next));
	Next[0] = -1;
	while(i < len){
		if(j == -1 || str[i] == str[j]){
			//if(str[i] == str[j])Next[++i] = ++j;
			//else j = Next[j];
			Next[++i] = ++j;
		}
		else j = Next[j];
	}
}

void out(){
	for(int i = 0; i < len; ++ i)
		printf("%d ", Next[i]);
	printf("\n");
}

int main(){
	while(~scanf("%s", str) && strcmp(str, ".")){
		len = strlen(str);
		Get_next();
		//out();
		if(len == 1)printf("1\n");
		else if(Next[len-1] == len - 2 && str[len-1] == str[len-2])printf("%d\n", len);
		else{
			int nxt = len - 1;
			while(true){
				if(Next[nxt] == 0)break;
				if(str[nxt] != str[Next[nxt]])break;
				nxt = Next[nxt];
			}
			printf("%d / %d = %d\n", len, nxt + 1, len / (nxt + 1));
		}
	}
	return 0;
}

/**

abcd
aaaa
ababab
.

yhebteblbyhebteblbyhebteblb
nerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpeznerwdpez
wccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwccwcc
yxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyx
yrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymuyrxmszymu
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
nypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejcnypdejc
lhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcjlhwzcj
ctctctctctctctctctctct
gdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqugdqu
rbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnvrbnv
epkqyxlepkqyxlepkqyxlepkqyxlepkqyxl
iitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiitiit
wwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyjwwauasyj
kmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvskmrjvs
bjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwobjllyrcwo
nvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccynvqccy
fysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjofysknzjo
dgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgddgd
kxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizcivkxdizciv
.

请按任意键继续. . .

*/