#!/usr/bin/python

import random

T = 100;

print(T);
for i in range(T):
	n = 100;
	flag = random.randint(0, 4);
	print(n);
	if(flag == 0):
		for j in range(n):
			print(random.randint(-200000, 200000), random.randint(1, 100));
	elif(flag == 1):
		basep = random.randint(-100000, 100000);
		basev = 1;
		for j in range(n):
			basep += random.randint(0, 120);
			print(basep, basev)
			basev += 1;
	elif(flag == 2):
		basep = random.randint(-100000, 100000);
		basev = 100;
		for j in range(n):
			basep -= random.randint(0, 120);
			print(basep, basev);
			basev -= 1;
	elif(flag == 3):
		basep = random.randint(-100000, 100000);
		basev = 1;
		for j in range(n):
			basep += random.randint(0, 120);
			print(basep, basev);
			basev -= 1;
	elif(flag == 4):
		basep = random.randint(-100000, 100000);
		basev = 100;
		for j in range(n):
			basep -= random.randint(1, 120);
			print(basep, basev);
			basev += 1;
	print();