#!/bin/bash

# Compile solution
if ! test -e exe/sol
then
	g++ src/sol.cpp -o exe/sol
	echo -e "src/sol.cpp compiled\n"
fi

# Generate input data
exe/datagen > data/in.in
echo -e "Input data generated\n"

# Run the program
echo "Running..."
time exe/sol < data/in.in > data/out.out
echo -e "\nProgram finished\n"
echo
cat data/out.out
