#!/usr/bin/python

import random

T = 100;
print(T);
for qwertyuiop in range(T):
	n = 1000;
	k = random.randint(1, 60);
	print(n, k);
	for i in range(n):
		print("%d " % random.randint(1, 10000000), end="");
	print();
